spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://aws.connect.psdb.cloud/ecommerce?useTimezone=true&serverTimezone=UTC&createDatabaseIfNotExist=true
    username: sauuy4buwe88fr50cpo8
    password: 
  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    show-sql: true
springdoc:
  paths-to-match:
    - /api/*/v1/*
  swagger-ui:
    use-root-path: true