spring:
  profiles:
    active: default
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    # url: ${DB_URL}?useTimezone=true&serverTimezone=UTC&createDatabaseIfNotExist=true
    # username: ${DB_USERNAME}
    # password: ${DB_PASSWORD}
    # url: ${DB_URL2}
    # username: ${DB_USERNAME2}
    # password: ${DB_PASSWORD2}

    url: jdbc:mysql://localhost:3306/ecommerce?useTimezone=true&serverTimezone=UTC&createDatabaseIfNotExist=true
    username: root
    password: S@m16162
  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    show-sql: true
springdoc:
  paths-to-match:
    - /api/v1/*/*
    - /api/v1/*
  swagger-ui:
    use-root-path: true