spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ecommerce?useTimezone=true&serverTimezone=UTC
    username: root
    password:   S@m16162
  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    show-sql: true
springdoc:
  paths-to-match:
    - /api/**/v1/**
  swagger-ui:
    use-root-path: true